#!/bin/bash
#######################################################
# USE
#
# cd /var/www/html; bash GitBackupBash
#
#######################################################
cd /var/www/html
mysqldump --user=root --password= --host=localhost --port=3306 --result-file="/var/www/html/database/word_database.sql" --databases "word"
git add -A
git commit -m "backup database from VPS"
git push